Repository GIScience/openrouteservice, pull requests merged in 2023-09, with the labels that each got.

#1535 fix: maxcellnodes parameter
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
Labels: fix

#1536 chore: update maven repository
  CHANGELOG.md
  pom.xml
Labels: dependencies, ignore-for-release

#1537 chore: update maven repository
  CHANGELOG.md
  pom.xml
Labels: ignore-for-release

#1538 fix(fastisochrones): Fix the max visited nodes bug for fast-isochrones
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/fastisochrones/Eccentricity.java
  ors-engine/src/main/java/org/heigit/ors/matrix/algorithms/dijkstra/DijkstraMatrixAlgorithm.java
  ors-engine/src/main/java/org/heigit/ors/routing/algorithms/AbstractOneToManyRoutingAlgorithm.java
  ors-engine/src/main/java/org/heigit/ors/routing/algorithms/DijkstraOneToManyAlgorithm.java
Labels: fix

#1539 fix(fastisochrones): Fix the max visited nodes break for fast-isochrones
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/matrix/algorithms/dijkstra/DijkstraMatrixAlgorithm.java
  ors-engine/src/main/java/org/heigit/ors/routing/algorithms/AbstractOneToManyRoutingAlgorithm.java
  ors-engine/src/main/java/org/heigit/ors/routing/algorithms/DijkstraOneToManyAlgorithm.java
Labels: fix

#1541 docs: Update Installation-and-Usage.md
  docs/installation/Installation-and-Usage.md
Labels: documentation

#1547 fix: bug in condition at TrafficEdgeFilter.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/edgefilters/TrafficEdgeFilter.java
Labels: fix

#1542 fix: RPM adjustments
  .github/workflows/rpm-build.yml
  .rpm-packaging/dockerfile-jboss-java17-rhel8
  .rpm-packaging/dockerfile-ubi8-java17-jws57
  .rpm-packaging/example-config.json
  .rpm-packaging/ors-war.spec
  .rpm-packaging/rhel8_post_install_check.sh
  .rpm-packaging/rhel8_post_uninstall_check.sh
  .rpm-packaging/rhel8_pre_install_check.sh
  .rpm-packaging/rhel8_pre_uninstall_check.sh
  .rpm-packaging/scripts/helper_functions.sh
  docs/installation/Installation-and-Usage.md
  ors-api/pom.xml
  ors-api/src/main/java/org/heigit/ors/api/Application.java
  ors-api/src/main/resources/logs/DEBUG_LOGGING.json
  ors-api/src/main/resources/logs/DEFAULT_LOGGING.json
  ors-api/src/main/resources/logs/PRODUCTION_LOGGING.json
  ors-api/src/test/resources/logs/TEST_LOGGING.json
  ors-engine/pom.xml
  ors-engine/src/main/java/org/heigit/ors/config/AppConfig.java
  pom.xml
Labels: fix

#1548 test: re-enable test coverage measurement
  Dockerfile
  ors-report-aggregation/pom.xml
  pom.xml
Labels: test
