Repository GIScience/openrouteservice, pull requests merged in 2023-10, with the labels that each got.

#1552 fix: change SRID in query for backwards compatibility
  ors-engine/src/main/java/org/heigit/ors/isochrones/statistics/postgresql/PostgresSQLStatisticsProvider.java
Labels: fix

#1554 fix: default location for transitional JSON configuration file
  docker-compose.yml
  docker-entrypoint.sh
  docs/installation/Running-with-Docker.md
  ors-engine/src/main/java/org/heigit/ors/config/AppConfig.java
Labels: fix

#1558 feat: add x-ors-version extension to OpenAPI info
  ors-api/src/main/java/org/heigit/ors/api/OpenAPIConfig.java
  ors-api/src/test/java/org/heigit/ors/apitests/openapi/ResultTest.java
Labels: feature

#1559 refactor(snap): Refactor parameters for clarity
  ors-api/src/main/java/org/heigit/ors/api/requests/snapping/SnappingApiRequest.java
  ors-api/src/test/java/org/heigit/ors/apitests/snapping/ParamsTest.java
Labels: refactor

#1562 refactor(rpm): Fix docker image to use rpm package
  .github/workflows/rpm-build.yml
  .rpm-packaging/dockerfile-ubi8-java17-jws57
  .rpm-packaging/ors-war.spec
  docs/installation/Installation-and-Usage.md
  ors-api/pom.xml
  ors-engine/pom.xml
  pom.xml
Labels: refactor

#1563 fix: change jws5 deps
  .rpm-packaging/ors-war.spec
  ors-api/pom.xml
  ors-engine/pom.xml
  pom.xml
Labels: fix

#1564 fix: redundant docker build
  .github/workflows/rpm-build.yml
Labels: fix

#1565 fix(pom): Fix broken jacoco version
  pom.xml
Labels: fix

#1566 fix(isochrones): use correct edge filter for snapping
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/isochrones/GraphEdgeMapFinder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/DistanceWeighting.java
Labels: fix

#1568 fix(isochrones): use correct edge filter for snapping
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/isochrones/GraphEdgeMapFinder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/DistanceWeighting.java
  ors-engine/src/main/java/org/heigit/ors/util/ProfileTools.java
Labels: fix

#1569 build(deps): bump org.json:json from 20230227 to 20231013
  pom.xml
Labels: build

#1570 fix(fastisochrones): use correct edge filter fast-isochrones snapping
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/fast/FastIsochroneMapBuilder.java
Labels: fix

#1572 fix(fastisochrones): use correct edge filter fast-isochrones snapping
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/fast/FastIsochroneMapBuilder.java
Labels: fix

#1577 fix(graphbuilder): Add a graph folder creation routine if the base fo…
  .github/workflows/run_maven_tests.yml
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphFileManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphManager.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphFileManagerTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphRepoManagerTest.java
Labels: fix

#1578 test: Migrate tests to temp folders
  ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListener.java
  ors-api/src/test/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListenerTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphFileManagerTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphManagerTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphRepoManagerTest.java
Labels: test

#1582 feat: profile hash update not activated graphs
  docs/documentation/Graph-Management.md
  ors-api/src/main/java/org/heigit/ors/api/services/GraphService.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/GraphInfo.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphFileManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphRepoManager.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphRepoManagerTest.java
Labels: feature

#1584 fix: suppress empty legs property in routing JSON responses
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/json/JSONIndividualRouteResponse.java
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
Labels: fix

#1590 docs: Update Badges in README.md
  README.md
Labels: documentation

#1589 fix: Set right permissions for the openrouteservice folders and files
  .rpm-packaging/ors-war.spec
  .rpm-packaging/rhel8_post_install_check.sh
  .rpm-packaging/scripts/helper_functions.sh
  docs/installation/Installation-and-Usage.md
Labels: fix
