Repository GIScience/openrouteservice, pull requests merged in 2023-06, with the labels that each got.

#1458 ci(docker): Fix the docker build github workflow
  .github/workflows/build-and-publish.yml
  .github/workflows/publish-tagged-release.yml
  .github/workflows/vulnerability-scanning.yml
  Dockerfile
Labels: ci

#1462 fix: include log4j.properties in docker setup
  Dockerfile
Labels: fix

#1461 fix: pass correct profile name to Dijkstra matrix
  openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  openrouteservice/src/test/java/org/heigit/ors/apitests/matrix/ResultTest.java
Labels: fix

#1459 chore: Update SQL query code for obtaining population data and add test
  CHANGELOG.md
  openrouteservice/src/main/java/org/heigit/ors/isochrones/statistics/postgresql/PostgresSQLStatisticsProvider.java
Labels: ignore-for-release

#1464 fix(cve): Upgrade kafka_2.13 from 3.4.0 to 3.4.1
  CHANGELOG.md
  openrouteservice/pom.xml
Labels: fix

#1449 fix(api-tests): Test based on mock HERE traffic data
  CHANGELOG.md
  openrouteservice/pom.xml
  openrouteservice/src/main/java/org/heigit/ors/api/ApiConfig.java
  openrouteservice/src/main/java/org/heigit/ors/mapmatching/GhMapMatcher.java
  openrouteservice/src/main/java/org/heigit/ors/routing/configuration/RouteProfileConfiguration.java
  openrouteservice/src/main/java/org/heigit/ors/routing/configuration/RoutingManagerConfiguration.java
  openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java
  openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSWeightingFactory.java
  openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/edgefilters/core/TrafficSpeedCoreEdgeFilter.java
  openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/reader/traffic/TrafficLink.java
  openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/TrafficGraphStorage.java
  openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HereTrafficGraphStorageBuilder.java
  openrouteservice/src/main/java/org/heigit/ors/routing/traffic/TrafficSpeedCalculator.java
  openrouteservice/src/test/files/data/traffic_data/here/Streets.dbf
  openrouteservice/src/test/files/data/traffic_data/here/Streets.shp
  openrouteservice/src/test/files/data/traffic_data/here/Streets.shx
  openrouteservice/src/test/files/data/traffic_data/here/ref_pattern.csv
  openrouteservice/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
  openrouteservice/src/test/java/org/heigit/ors/routing/traffic/TrafficSpeedCalculatorTest.java
  openrouteservice/src/test/resources/ors-config.json
Labels: fix

#1467 chore: Release 7.1.0
  CHANGELOG.md
  openrouteservice/pom.xml
Labels: ignore-for-release

#1471 docs(readme): update GH version
  README.md
Labels: documentation

#1465 chore: #1456 redo GitHub templates
  .github/ISSUE_TEMPLATE/api_issue.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/simple.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTE.md
  ISSUE_TEMPLATE.md
Labels: ignore-for-release

#1475 fix(cve): Upgrade kafka_2.13 from 3.4.0 to 3.5.0
  CHANGELOG.md
  pom.xml
Labels: fix

#1476 fix(cve): Remove maven-gpg-plugin and maven-shared-utils
  CHANGELOG.md
  ors-api/pom.xml
  pom.xml
Labels: fix

#1477 fix(cve): Upgrade spring-boot from 2.7.10 to 2.7.12
  CHANGELOG.md
  pom.xml
Labels: fix

#1478 chore: Add security issue template
  .github/ISSUE_TEMPLATE/api_issue.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/security.yml
  .github/ISSUE_TEMPLATE/simple.yml
Labels: ignore-for-release

#1480 fix(cve): Upgrade org.geotools.gt-epsg-hsql to version 29.1.
  CHANGELOG.md
  pom.xml
Labels: fix

#1481 fix: clean up and remove unnecessary code
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/controllers/CentralityAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/ExportAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/StatusAPI.java
  ors-api/src/main/java/org/heigit/ors/api/requests/centrality/CentralityRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/centrality/CentralityRequestEnums.java
  ors-api/src/main/java/org/heigit/ors/api/requests/common/APIRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/export/ExportRequest.java
  ors-api/src/main/java/org/heigit/ors/api/responses/centrality/CentralityResponse.java
  ors-api/src/main/java/org/heigit/ors/api/responses/centrality/json/JsonCentralityLocation.java
  ors-api/src/main/java/org/heigit/ors/api/responses/centrality/json/JsonCentralityResponse.java
  ors-api/src/main/java/org/heigit/ors/api/responses/centrality/json/JsonEdgeScore.java
  ors-api/src/main/java/org/heigit/ors/api/responses/centrality/json/JsonNodeScore.java
  ors-api/src/test/java/org/heigit/ors/apitests/centrality/ParamsTest.java
  ors-api/src/test/java/org/heigit/ors/apitests/centrality/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/centrality/CentralityErrorCodes.java
  ors-engine/src/main/java/org/heigit/ors/centrality/CentralityRequest.java
  ors-engine/src/main/java/org/heigit/ors/centrality/CentralityResult.java
  ors-engine/src/main/java/org/heigit/ors/centrality/CentralityWarning.java
  ors-engine/src/main/java/org/heigit/ors/centrality/algorithms/AbstractCentralityAlgorithm.java
  ors-engine/src/main/java/org/heigit/ors/centrality/algorithms/CentralityAlgorithm.java
  ors-engine/src/main/java/org/heigit/ors/centrality/algorithms/brandes/BrandesCentralityAlgorithm.java
  ors-engine/src/main/java/org/heigit/ors/mapmatching/hmm/HiddenMarkovMapMatcher.java
  ors-engine/src/main/java/org/heigit/ors/mapmatching/hmm/ViterbiSolver.java
  ors-engine/src/main/java/org/heigit/ors/routing/APIEnums.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfilesUpdater.java
  ors-engine/src/main/java/org/heigit/ors/routing/configuration/RouteUpdateConfiguration.java
  ors-engine/src/main/java/org/heigit/ors/routing/configuration/RoutingManagerConfiguration.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java
  ors-engine/src/test/java/org/heigit/ors/centrality/CentralityAlgorithmTest.java
Labels: fix

#1482 chore: remove ORSKafkaConsumer and related code
  CHANGELOG.md
  ors-api/pom.xml
  ors-api/src/main/java/org/heigit/ors/api/Application.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/StatusAPI.java
  ors-api/src/main/java/org/heigit/ors/api/kafka/ORSKafkaConsumer.java
  ors-api/src/main/java/org/heigit/ors/api/kafka/ORSKafkaConsumerConfiguration.java
  ors-api/src/main/java/org/heigit/ors/api/kafka/ORSKafkaConsumerRunner.java
  ors-api/src/main/java/org/heigit/ors/api/kafka/ORSKafkaTestCluster.java
  ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSKafkaConsumerInitContextListener.java
  ors-api/src/test/java/org/heigit/ors/apitests/status/ResultTest.java
  ors-api/src/test/resources/logs/TEST_LOGGING.json
  ors-api/src/test/resources/ors-config.json
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/ExpiringSpeedStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/ExpiringSpeedGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/util/ExpiringSpeedCalculator.java
  ors-engine/src/main/resources/META-INF/services/org.heigit.ors.routing.graphhopper.extensions.storages.builders.GraphStorageBuilder
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/storages/ExpiringSpeedStorageTest.java
  ors-engine/src/test/resources/ors-config.json
  pom.xml
Labels: ignore-for-release

#1483 chore(matrix): Clean-up path metrics extractor for matrix Dijkstra
  ors-engine/src/main/java/org/heigit/ors/matrix/PathMetricsExtractor.java
Labels: ignore-for-release

#1484 fix: re-introduce edge metrics cache
  ors-engine/src/main/java/org/heigit/ors/matrix/PathMetricsExtractor.java
  ors-engine/src/main/java/org/heigit/ors/matrix/algorithms/dijkstra/DijkstraMatrixAlgorithm.java
Labels: fix
