Repository GIScience/openrouteservice, pull requests merged in 2023-11, with the labels that each got.

#1592 fix: Set permission to read-only for the war file
  .rpm-packaging/ors-war.spec
  .rpm-packaging/rhel8_post_install_check.sh
  .rpm-packaging/scripts/helper_functions.sh
Labels: fix

#1593 feat: logging-iso-timestamp
  ors-api/src/main/resources/logs/DEBUG_LOGGING.json
  ors-api/src/main/resources/logs/DEFAULT_LOGGING.json
  ors-api/src/main/resources/logs/PRODUCTION_LOGGING.json
  ors-api/src/test/resources/logs/TEST_LOGGING.json
  ors-api/src/test/resources/logs/UNITTEST_LOGGING.json
Labels: feature

#1594 fix: log rotation with CronTriggeringPolicy, set by ENV
  .rpm-packaging/ors-war.spec
  docs/installation/Installation-and-Usage.md
  ors-api/src/main/resources/logs/DEBUG_LOGGING.json
  ors-api/src/main/resources/logs/DEFAULT_LOGGING.json
  ors-api/src/main/resources/logs/PRODUCTION_LOGGING.json
  ors-api/src/test/resources/logs/TEST_LOGGING.json
Labels: fix

#1596 ci: bump snapshot version
  ors-api/pom.xml
  ors-engine/pom.xml
  pom.xml
Labels: ci

#1595 chore: log openrouteservice version and build date
  ors-api/src/main/java/org/heigit/ors/api/Application.java
  ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListener.java
Labels: ignore-for-release

#1597 fix: revert rotated log files to being gzipped
  ors-api/src/main/resources/logs/DEBUG_LOGGING.json
  ors-api/src/main/resources/logs/DEFAULT_LOGGING.json
  ors-api/src/main/resources/logs/PRODUCTION_LOGGING.json
  ors-api/src/test/resources/logs/TEST_LOGGING.json
Labels: fix

#1598 feat: selinux semanage by RPM
  .github/workflows/rpm-build.yml
  .rpm-packaging/.rpm_selinux_testing.sh
  .rpm-packaging/dockerfile-ubi8-java17-jws57
  .rpm-packaging/ors-selinux.spec
  .rpm-packaging/rhel8_post_install_check.sh
  .rpm-packaging/scripts/helper_functions.sh
  docs/installation/Installation-and-Usage.md
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-engine/src/main/java/org/heigit/ors/config/AppConfig.java
  pom.xml
Labels: feature

#1600 docs: add description for selinux package
  docs/installation/Installation-and-Usage.md
Labels: documentation

#1601 fix: correct elevation cache path
  .github/workflows/rpm-build.yml
  .gitignore
  .rpm-packaging/example-config.json
  .rpm-packaging/ors-war.spec
  .rpm-packaging/rhel8_post_install_check.sh
  .rpm-packaging/rhel8_post_uninstall_check.sh
  docs/installation/Installation-and-Usage.md
  ors-api/src/main/resources/ors-config-sample.json
  ors-engine/src/test/resources/ors-config.json
Labels: fix

#1587 feat: enrich graph metadata
  ors-api/src/main/java/org/heigit/ors/api/EngineProperties.java
  ors-api/src/main/java/org/heigit/ors/api/ORSGraphInfoV1ProfilePropertiesBuilder.java
  ors-api/src/test/java/org/heigit/ors/api/ORSGraphInfoV1ProfilePropertiesBuilderTest.java
  ors-engine/src/main/java/org/heigit/ors/routing/configuration/RouteProfileConfiguration.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphInfoV1.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphInfoV1ProfileProperties.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphFileManagerTest.java
Labels: feature

#1604 build: Release 7.1.1
  CHANGELOG.md
Labels: build

#1605 fix: BKG findings v7.2.x-SNAPSHOT-8
  docs/installation/Installation-and-Usage.md
Labels: fix

#1610 build: V7.2.x release preparation
  .github/workflows/rpm-build.yml
  .rpm-packaging/example.repo
  CHANGELOG.md
  docs/installation/Configuration.md
  docs/installation/Installation-and-Usage-with-JWS.md
  docs/installation/Installation-and-Usage.md
  ors-api/pom.xml
  ors-api/src/main/java/org/heigit/ors/api/ORSEnvironmentPostProcessor.java
  ors-api/src/test/java/org/heigit/ors/apitests/isochrones/ResultTest.java
  ors-engine/pom.xml
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/concaveballs/ConcaveBallsIsochroneMapBuilder.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/statistics/postgresql/PostgresSQLStatisticsProvider.java
  pom.xml
Labels: build

#1612 ci: fix release upload
  .github/workflows/rpm-build.yml
Labels: ci

#1613 ci: fix asset upload
  .github/workflows/rpm-build.yml
Labels: ci

#1619 fix: accidential execution rpm postun
  .rpm-packaging/ors-selinux.spec
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  pom.xml
Labels: fix
