Repository GIScience/openrouteservice, pull requests merged in 2023-05, with the labels that each got.

#1424 ci(workflow): Add conventional commit checks
  .github/release.yml
  .github/workflows/commit-style.yml
Labels: ci

#1437 fix(pom): Upgrade org.apache.curator:curator-test from 5.4.0 to 5.5.0
  openrouteservice/pom.xml
Labels: fix

#1442 ci(github): Reduce noise from actions labeling
  .github/workflows/conventional-commit.yml
  .github/workflows/conventional-label.yml
Labels: ci

#1432 ci(cve): Scan the war and docker images with grype
  .github/workflows/vulnerability-scanning.yml
Labels: ci

#1445 fix(cve): Bump spring-boot version from 2.7.11 to 2.7.12
  openrouteservice/pom.xml
Labels: fix

#1430 fix(map-matching): Fix broken map matching for here traffic data
  CHANGELOG.md
  openrouteservice/src/main/java/org/heigit/ors/mapmatching/hmm/HiddenMarkovMapMatcher.java
  openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java
  openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HereTrafficGraphStorageBuilder.java
Labels: fix

#1446 fix(cve): Remove maven-gpg-plugin and maven-shared-utils
  openrouteservice/pom.xml
Labels: high priority, fix

#1452 fix(cve): Upgrade to eclipse-temurin:17.0.7_7-jre-alpine (#1451)
  Dockerfile
Labels: fix

#1453 fix(cve): Upgrade tomcat for the docker setup from 8.5.69 9.0.75
  Dockerfile
Labels: fix

#1454 refactor: remove unused AccelerationWeighting
  CHANGELOG.md
  openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSWeightingFactory.java
  openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/AccelerationWeighting.java
Labels: refactor

#1457 fix: mapmatching candidate snaps
  CHANGELOG.md
  openrouteservice/pom.xml
  openrouteservice/src/main/java/org/heigit/ors/mapmatching/hmm/HiddenMarkovMapMatcher.java
Labels: fix
