Repository GIScience/openrouteservice, pull requests merged in 2023-08, with the labels that each got.

#1512 build: enable mvn spring-boot:run
  ors-api/pom.xml
  pom.xml
Labels: build

#1518 feat: RPM delivery
  .github/workflows/rpm-build.yml
  .rpm-packaging/Dockerfile-jboss
  .rpm-packaging/dockerfile-rhel8
  .rpm-packaging/ors-config.json
  .rpm-packaging/ors-war.spec
Labels: feature

#1511 fix: remove elevation smoother
  CHANGELOG.md
  ors-api/src/test/java/org/heigit/ors/apitests/matrix/ResultTest.java
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
  ors-api/src/test/resources/application-test.yml
  ors-engine/src/main/java/org/heigit/ors/routing/pathprocessors/ExtraInfoProcessor.java
  ors-engine/src/main/java/org/heigit/ors/routing/util/ElevationSmoother.java
  ors-engine/src/main/java/org/heigit/ors/util/PolylineEncoder.java
  ors-engine/src/test/java/org/heigit/ors/util/PolyLineEncoderTest.java
Labels: fix

#1521 refactor: move loosly related members out of RoutingProfile
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/EngineProperties.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/configuration/RoutingManagerConfiguration.java
  ors-engine/src/main/java/org/heigit/ors/util/ProfileTools.java
  ors-engine/src/test/java/org/heigit/ors/fastisochrones/partitioning/FastIsochroneFactoryTest.java
Labels: refactor

#1522 feat: Enhance the RPM build
  .github/workflows/rpm-build.yml
  .github/workflows/run_maven_tests.yml
  .github/workflows/vulnerability-scanning.yml
  .rpm-packaging/dockerfile-jboss-java17-rhel8
  .rpm-packaging/ors-war.spec
  .rpm-packaging/rhel8_post_install_check.sh
  .rpm-packaging/rhel8_post_uninstall_check.sh
  .rpm-packaging/rhel8_pre_install_check.sh
  .rpm-packaging/scripts/helper_functions.sh
Labels: feature

#1526 ci: Add rpm Nexus publish and testing workflow
  .github/utils/check_nexus_repo_exists.sh
  .github/utils/clean_nexus_repo_folder.sh
  .github/utils/helper/helper_functions.sh
  .github/utils/upload_rpm_package.sh
  .github/utils/url_check.sh
  .github/workflows/build-and-publish.yml
  .github/workflows/build_graph.yml
  .github/workflows/rpm-build.yml
  .rpm-packaging/example-config.json
  .rpm-packaging/example.repo
  .rpm-packaging/ors-war.spec
  .rpm-packaging/rhel8_post_install_check.sh
  .rpm-packaging/rhel8_post_uninstall_check.sh
  .rpm-packaging/rhel8_pre_install_check.sh
  docs/installation/Installation-and-Usage.md
  ors-api/pom.xml
  ors-engine/pom.xml
  pom.xml
Labels: ci

#1527 fix: Fix the snapshots upload location and the snapshot release version
  .github/workflows/rpm-build.yml
  ors-api/pom.xml
  ors-engine/pom.xml
  pom.xml
Labels: fix

#1530 feat: make log location configurable via env var
  .github/workflows/rpm-build.yml
  .rpm-packaging/ors-war.spec
  .rpm-packaging/rhel8_post_install_check.sh
  .rpm-packaging/rhel8_post_uninstall_check.sh
  .rpm-packaging/rhel8_pre_uninstall_check.sh
  ors-api/src/main/resources/logs/DEBUG_LOGGING.json
  ors-api/src/main/resources/logs/DEFAULT_LOGGING.json
  ors-api/src/main/resources/logs/PRODUCTION_LOGGING.json
  ors-api/src/test/resources/logs/TEST_LOGGING.json
Labels: feature

#1531 feat: make log location configurable via env var
  ors-api/src/main/resources/logs/DEBUG_LOGGING.json
  ors-api/src/main/resources/logs/DEFAULT_LOGGING.json
  ors-api/src/main/resources/logs/PRODUCTION_LOGGING.json
  ors-api/src/test/resources/logs/TEST_LOGGING.json
Labels: feature

#1534 fix: remove visited nodes limit from fast isochrones preparations
  ors-engine/src/main/java/org/heigit/ors/fastisochrones/Eccentricity.java
Labels: fix
