Repository GIScience/openrouteservice, pull requests merged in 2023-07, with the labels that each got.

#1487 fix: openapi playground parsing
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/SwaggerConfig.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/ExportAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/IsochronesAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/MatrixAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/RoutingAPI.java
  ors-api/src/main/java/org/heigit/ors/api/requests/common/APIRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/common/RequestOptions.java
  ors-api/src/main/java/org/heigit/ors/api/requests/export/ExportRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/isochrones/IsochronesRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RequestProfileParams.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RequestProfileParamsRestrictions.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RequestProfileParamsWeightings.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RouteRequest.java
  ors-api/src/main/java/org/heigit/ors/api/responses/isochrones/IsochronesResponseInfo.java
  ors-api/src/main/java/org/heigit/ors/api/responses/isochrones/geojson/GeoJSONIsochroneProperties.java
  ors-api/src/main/java/org/heigit/ors/api/responses/matrix/MatrixResponseInfo.java
  ors-api/src/main/java/org/heigit/ors/api/responses/matrix/json/JSONLocation.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/RouteResponseInfo.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/geojson/GeoJSONSummary.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/json/JSONIndividualRouteResponse.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/json/JSONLeg.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/json/JSONSegment.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/json/JSONStep.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/json/JSONSummary.java
  ors-api/src/main/resources/application.yml
  ors-api/src/test/java/org/heigit/ors/apitests/swagger/ResultTest.java
Labels: fix

#1502 ci: disable rpm build on pull
  .github/workflows/rpm-build.yml
Labels: ci

#1503 refactor: move logic from Request classes to new service layer
  ors-api/src/main/java/org/heigit/ors/api/EndpointsProperties.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/ExportAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/IsochronesAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/MatrixAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/RoutingAPI.java
  ors-api/src/main/java/org/heigit/ors/api/requests/common/APIRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/export/ExportRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/isochrones/IsochronesRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RouteRequest.java
  ors-api/src/main/java/org/heigit/ors/api/services/ApiService.java
  ors-api/src/main/java/org/heigit/ors/api/services/ExportService.java
  ors-api/src/main/java/org/heigit/ors/api/services/IsochronesService.java
  ors-api/src/main/java/org/heigit/ors/api/services/MatrixService.java
  ors-api/src/main/java/org/heigit/ors/api/services/RoutingService.java
  ors-api/src/main/java/org/heigit/ors/api/util/AppConfigMigration.java
  ors-api/src/main/resources/application.yml
  ors-api/src/test/java/org/heigit/ors/api/services/APIServiceTest.java
  ors-api/src/test/java/org/heigit/ors/api/services/IsochronesServiceTest.java
  ors-api/src/test/java/org/heigit/ors/api/services/MatrixServiceTest.java
  ors-api/src/test/java/org/heigit/ors/api/services/RoutingServiceTest.java
Labels: refactor

#1501 fix(gtfs): use GH v4.8.2 to resolve issue with old jts-core version
  CHANGELOG.md
  ors-engine/pom.xml
Labels: on hold :hand:, fix

#1508 perf(isochrones): Increase edge splitting threshold
  CHANGELOG.md
  ors-api/src/test/java/org/heigit/ors/apitests/isochrones/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/concaveballs/ConcaveBallsIsochroneMapBuilder.java
Labels: performance
