Repository GIScience/openrouteservice, pull requests merged in 2024-03, with the labels that each got.

#1702 test: Add integration tests for maven and jar deployments
  .github/workflows/integration-tests.yml
  .gitignore
  .integration-scenarios/debian-12-jar-mvn/Dockerfile-jar
  .integration-scenarios/debian-12-jar-mvn/Dockerfile-jar.dockerignore
  .integration-scenarios/debian-12-jar-mvn/Dockerfile-mvn
  .integration-scenarios/debian-12-jar-mvn/Dockerfile-mvn.dockerignore
  .integration-scenarios/debian-12-jar-mvn/files/.build-graph.sh
  .integration-scenarios/debian-12-jar-mvn/files/test.conf
  .integration-scenarios/debian-12-jar-mvn/files/testfunctions.sh
  .integration-scenarios/debian-12-jar-mvn/run.sh
  .integration-scenarios/debian-12-jar-mvn/tests/_only-jar-missing-config-but-profile-enabled-as-env-dot.sh
  .integration-scenarios/debian-12-jar-mvn/tests/arg-overrides-default-prop.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-all-graphs.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-bike-electric.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-bike-mountain.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-bike-regular.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-bike-road.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-car.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-hgv.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-hiking.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-public-transport.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-walking.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-wheelchair.sh
  .integration-scenarios/debian-12-jar-mvn/tests/check-avoid-area-car.sh
  .integration-scenarios/debian-12-jar-mvn/tests/lookup-yml-in-etc.sh
  .integration-scenarios/debian-12-jar-mvn/tests/lookup-yml-in-userconf.sh
  .integration-scenarios/debian-12-jar-mvn/tests/lookup-yml-in-workdir.sh
  .integration-scenarios/debian-12-jar-mvn/tests/lookup-yml-prefer-userconf-over-etc.sh
  .integration-scenarios/debian-12-jar-mvn/tests/lookup-yml-prefer-workdir-over-userconf.sh
  .integration-scenarios/debian-12-jar-mvn/tests/missing-config-but-pbf-and-profile-enabled-as-arg.sh
  .integration-scenarios/debian-12-jar-mvn/tests/missing-config-but-pbf-and-profile-enabled-as-env-upper.sh
  .integration-scenarios/debian-12-jar-mvn/tests/missing-config.sh
  .integration-scenarios/debian-12-jar-mvn/tests/specify-yml-prefer-arg-over-env.sh
  .integration-scenarios/debian-12-jar-mvn/tests/specify-yml-prefer-arg-over-lookup.sh
  .integration-scenarios/debian-12-jar-mvn/tests/specify-yml-prefer-env-over-lookup.sh
  ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListener.java
Labels: test

#1712 docs: fix dead links
  docs/.vitepress/config.js
  docs/api-reference/index.md
  docs/contributing/backend-documentation.md
  docs/contributing/index.md
  docs/getting-started.md
  docs/run-instance/building-from-source.md
  docs/run-instance/configuration/index.md
  docs/run-instance/configuration/json.md
  docs/run-instance/configuration/ors/engine/profiles.md
  docs/run-instance/data.md
  docs/run-instance/running-jar.md
  docs/run-instance/running-war.md
Labels: documentation

#1707 test: Add war deployment integration test
  .github/workflows/integration-tests.yml
  .github/workflows/release-artifacts.yml
  .github/workflows/rpm-build.yml
  .github/workflows/run_maven_tests.yml
  .github/workflows/vulnerability-scanning.yml
  .gitignore
  .integration-scenarios/debian-12-jar-mvn/files/.build-graph.sh
  .integration-scenarios/debian-12-jar-mvn/files/test.conf
  .integration-scenarios/debian-12-jar-mvn/files/testfunctions.sh
  .integration-scenarios/debian-12-jar-mvn/run.sh
  .integration-scenarios/debian-12-jar-mvn/tests/_only-jar-missing-config-but-profile-enabled-as-env-dot.sh
  .integration-scenarios/debian-12-jar-mvn/tests/arg-overrides-default-prop.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-all-graphs.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-bike-electric.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-bike-mountain.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-bike-regular.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-bike-road.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-car.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-hgv.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-hiking.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-public-transport.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-walking.sh
  .integration-scenarios/debian-12-jar-mvn/tests/build-graph-wheelchair.sh
  .integration-scenarios/debian-12-jar-mvn/tests/check-avoid-area-car.sh
  .integration-scenarios/debian-12-jar-mvn/tests/lookup-yml-in-etc.sh
  .integration-scenarios/debian-12-jar-mvn/tests/lookup-yml-in-userconf.sh
  .integration-scenarios/debian-12-jar-mvn/tests/lookup-yml-in-workdir.sh
  .integration-scenarios/debian-12-jar-mvn/tests/lookup-yml-prefer-userconf-over-etc.sh
  .integration-scenarios/debian-12-jar-mvn/tests/lookup-yml-prefer-workdir-over-userconf.sh
  .integration-scenarios/debian-12-jar-mvn/tests/missing-config-but-pbf-and-profile-enabled-as-arg.sh
  .integration-scenarios/debian-12-jar-mvn/tests/missing-config-but-pbf-and-profile-enabled-as-env-upper.sh
  .integration-scenarios/debian-12-jar-mvn/tests/missing-config.sh
  .integration-scenarios/debian-12-jar-mvn/tests/specify-yml-prefer-arg-over-env.sh
  .integration-scenarios/debian-12-jar-mvn/tests/specify-yml-prefer-arg-over-lookup.sh
  .integration-scenarios/debian-12-jar-mvn/tests/specify-yml-prefer-env-over-lookup.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/Dockerfile
  .integration-scenarios/debian-12-tomcat-war-systemd/Dockerfile.dockerignore
  .integration-scenarios/debian-12-tomcat-war-systemd/helpers/1_logging.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/helpers/2_system.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/helpers/3_files.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/helpers/4_permissions.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/helpers/5_time.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/helpers/6_users.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/helpers/7_networking.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/helpers/8_openrouteservice.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/run.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/setup/install.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/setup/setenv.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/tests/0_test_default.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/tests/1_test_activate_second_profile_with_config.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/tests/2_test_activate_three_profiles_with_env.sh
  .integration-scenarios/debian-12-tomcat-war-systemd/tests/3_build_all_profiles.sh
  ors-api/src/main/java/org/heigit/ors/api/ORSEnvironmentPostProcessor.java
Labels: test

#1718 test: fix flaky jar mvn integration tests
  .integration-scenarios/debian-12-jar-mvn/Dockerfile-jar
  .integration-scenarios/debian-12-jar-mvn/Dockerfile-mvn
  .integration-scenarios/debian-12-jar-mvn/run.sh
Labels: test

#1708 fix(isochrones): correct and unify edge splitting
  CHANGELOG.md
  ors-api/src/test/java/org/heigit/ors/apitests/isochrones/ResultTest.java
  ors-api/src/test/java/org/heigit/ors/apitests/isochrones/fast/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/AbstractIsochroneMapBuilder.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/concaveballs/ConcaveBallsIsochroneMapBuilder.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/fast/FastIsochroneMapBuilder.java
Labels: fix

#1745 fix(config): Resolve absolute paths for the config
  ors-api/src/main/java/org/heigit/ors/api/EngineProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/EngineConfig.java
  ors-engine/src/main/java/org/heigit/ors/routing/configuration/RouteProfileConfiguration.java
Labels: fix

#1670 feat(docker): Introduce reworked docker setup with jar
  .dockerignore
  .github/utils/config_conversion.sh
  .github/utils/yml_config_to_ors_config_conversion.sh
  .github/utils/yml_config_to_properties_conversion.sh
  .github/utils/yml_config_validation.sh
  .github/workflows/config-conversion-automation.yml
  .github/workflows/docker-build-and-test.yml
  .github/workflows/publish-tagged-release.yml
  .github/workflows/release-artifacts.yml
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  docker-entrypoint.sh
  docs/run-instance/running-with-docker.md
  ors-api/src/main/resources/application.yml
  ors-config.env
  ors-config.yml
Labels: feature

#1750 feat(docs): custom 404 page
  docs/.vitepress/config.js
Labels: feature

#1746 docs: rewrite docu for docker setup
  .integration-scenarios/debian-12-jar-mvn/tests/specify-json-with-env-ors-config.sh
  CHANGELOG.md
  README.md
  docker-compose.yml
  docs/index.md
  docs/public/map-client-isochrones.png
  docs/run-instance/building-from-source.md
  docs/run-instance/configuration/index.md
  docs/run-instance/index.md
  docs/run-instance/running-jar.md
  docs/run-instance/running-war.md
  docs/run-instance/running-with-docker.md
Labels: documentation

#1754 feat: add config migration tool info
  docker-entrypoint.sh
  docs/run-instance/configuration/index.md
  docs/run-instance/configuration/json.md
  docs/run-instance/configuration/migrate-from-json.md
Labels: feature

#1748 fix: correctly resolve access to ways tagged with `hgv=delivery`
  CHANGELOG.md
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java
Labels: fix

#1757 ci(docker-build-and-test): add elevation_cache volume
  .github/workflows/docker-build-and-test.yml
Labels: ci

#1756 chore: release v8.0.0
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  pom.xml
Labels: ignore-for-release

#1758 docs: add missing graphs_data_access property info
  docs/run-instance/configuration/ors/engine/index.md
Labels: documentation

#1759 docs: document A* config parameters
  CHANGELOG.md
  docs/run-instance/configuration/ors/engine/profiles.md
Labels: documentation

#1764 docs: add warning for profile_default settings
  docs/run-instance/configuration/ors/engine/index.md
  docs/run-instance/configuration/ors/engine/profiles.md
Labels: documentation
