Repository GIScience/openrouteservice, pull requests merged in 2024-10, with the labels that each got.

#1853 fix: access to roads where transporting hazardous materials is forbidden
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/edgefilters/HeavyVehicleEdgeFilter.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/HeavyVehicleAttributesGraphStorage.java
Labels: fix

#1854 refactor: remove unused destination filter
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/edgefilters/HeavyVehicleEdgeFilter.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/HeavyVehicleAttributesGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/util/DestinationDependentEdgeFilter.java
Labels: refactor

#1859 feat: add Vietnamese translation
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/APIEnums.java
  ors-engine/src/main/resources/resources/locales/ors_vi-VN.resources
Labels: feature

#1862 feat: add Finnish translation
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/APIEnums.java
  ors-engine/src/main/resources/resources/locales/ors_fi-FI.resources
Labels: feature

#1863 chore: release v8.2.0
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  pom.xml
Labels: ignore-for-release

#1864 fix: use latest release in docker-compose download link
  docs/run-instance/running-with-docker.md
Labels: fix

#1872 docs: export endpoint live
  CHANGELOG.md
  README.md
  docs/.vitepress/config.js
  docs/api-reference/endpoints/export/index.md
  docs/api-reference/endpoints/index.md
  docs/api-reference/index.md
  docs/getting-started.md
  package-lock.json
  package.json
Labels: documentation

#1871 fix: failing queries that combine departure/arrival parameters with avoid areas
  CHANGELOG.md
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ParamsTest.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingRequest.java
  pom.xml
Labels: fix

#1875 fix: matrix limit not respected
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/services/MatrixService.java
  ors-api/src/test/java/org/heigit/ors/apitests/matrix/ParamsTest.java
Labels: fix

#1876 build: update spring dependency …
  pom.xml
Labels: build

#1877 ci: adapt and change creation of ors-config.yml
  .github/utils/yml_config_to_ors_config_conversion.sh
  .github/utils/yml_config_to_properties_conversion.sh
  .github/utils/yml_config_validation.sh
  ors-api/src/main/resources/application.yml
Labels: ci

#1879 feat: take into account `hazmat:B`, ..., `hazmat:E` tags
  CHANGELOG.md
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java
Labels: feature
