Repository GIScience/openrouteservice, pull requests merged in 2024-12, with the labels that each got.

#1921 chore: release v9.0.0
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  ors-test-scenarios/pom.xml
  pom.xml
Labels: ignore-for-release

#1924 chore: bump to new snapshot version
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  ors-test-scenarios/pom.xml
  pom.xml
Labels: ignore-for-release

#1925 fix: NPE caused by error handling code
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/controllers/ExportAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/IsochronesAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/MatrixAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/RoutingAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/SnappingAPI.java
Labels: fix

#1920 docs(setup): First draft for the tomcat 10, war setup example.
  docs/.vitepress/config.js
  docs/.vitepress/sidebars/versioned/v8.2.0.json
  docs/run-instance/example-setups/de_tomcat-10-ubuntu_22_04.md
  docs/run-instance/example-setups/en_tomcat-10-ubuntu_22_04.md
  docs/run-instance/example-setups/index.md
  docs/versions/v8.2.0/run-instance/example-setups/de_tomcat-10-ubuntu_22_04.md
  docs/versions/v8.2.0/run-instance/example-setups/en_tomcat-10-ubuntu_22_04.md
  docs/versions/v8.2.0/run-instance/example-setups/index.md
Labels: documentation

#1931 docs(status): update status response documentation
  docs/api-reference/endpoints/status/index.md
Labels: documentation

#1932 refactor: move build isochrones
  ors-api/src/main/java/org/heigit/ors/api/services/IsochronesService.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/IsochroneRequest.java
  ors-engine/src/main/java/org/heigit/ors/matrix/MatrixRequest.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingRequest.java
  ors-engine/src/main/java/org/heigit/ors/util/TemporaryUtilShelter.java
Labels: refactor

#1926 feat: Add topojson graph export rebase
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/APIEnums.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/ExportAPI.java
  ors-api/src/main/java/org/heigit/ors/api/requests/common/APIRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/export/ExportApiRequest.java
  ors-api/src/main/java/org/heigit/ors/api/responses/export/json/JsonExportResponse.java
  ors-api/src/main/java/org/heigit/ors/api/responses/export/topojson/Arc.java
  ors-api/src/main/java/org/heigit/ors/api/responses/export/topojson/Geometry.java
  ors-api/src/main/java/org/heigit/ors/api/responses/export/topojson/Network.java
  ors-api/src/main/java/org/heigit/ors/api/responses/export/topojson/Objects.java
  ors-api/src/main/java/org/heigit/ors/api/responses/export/topojson/Properties.java
  ors-api/src/main/java/org/heigit/ors/api/responses/export/topojson/TopoJsonExportResponse.java
  ors-api/src/main/java/org/heigit/ors/api/services/ExportService.java
  ors-api/src/test/java/org/heigit/ors/api/responses/export/topojson/TopoJsonExportResponseTest.java
  ors-api/src/test/java/org/heigit/ors/apitests/export/ParamsTest.java
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
  ors-api/src/test/resources/application-test.yml
  ors-engine/src/main/java/org/heigit/ors/export/ExportRequest.java
  ors-engine/src/main/java/org/heigit/ors/export/ExportResult.java
Labels: feature
