Repository GIScience/openrouteservice, pull requests merged in 2024-04, with the labels that each got.

#1772 fix: preparation mode not failing
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListener.java
Labels: fix

#1780 build: add tomcat keep-alive-timeout
  CHANGELOG.md
  ors-api/src/main/resources/application.yml
  ors-config.env
  ors-config.yml
Labels: build

#1776 docs(readme): Fix the docker shields
  README.md
Labels: documentation

#1775 docs: non-positive values of `maximum_grade_level` encoder config parameter
  CHANGELOG.md
  docs/run-instance/configuration/ors/engine/profiles.md
Labels: documentation
