Repository GIScience/openrouteservice, pull requests merged in 2024-07, with the labels that each got.

#1817 chore: update CHANGELOG and poms for release
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  pom.xml
Labels: ignore-for-release

#1820 feat: extended storage config classes
  ors-api/src/main/java/org/heigit/ors/api/config/EngineProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorage.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageCsvIndex.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageGreenIndex.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageHeavyVehicle.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageHereTraffic.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageHillIndex.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageNoiseIndex.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageOsmId.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageRoadAccessRestrictions.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageShadowIndex.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageTrailDifficulty.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageWayCategory.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageWaySurfaceType.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageWheelchair.java
  ors-api/src/main/java/org/heigit/ors/api/converters/PathDeserializer.java
  ors-api/src/main/java/org/heigit/ors/api/converters/PathSerializer.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageCsvIndexTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageGreenIndexTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageHeavyVehicleTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageHereTrafficTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageHillIndexTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageNoiseIndexTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageOsmIdTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageRoadAccessRestrictionsTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageShadowIndexTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageTrailDifficultyTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageWayCategoryTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageWaySurfaceTypeTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageWheelchairTest.java
  ors-api/src/test/java/org/heigit/ors/api/converters/PathDeserializerTest.java
  ors-api/src/test/java/org/heigit/ors/api/converters/PathSerializerTest.java
Labels: feature

#1818 chore: Post release cleanup
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  pom.xml
Labels: ignore-for-release

#1821 fix: dynamically size extra info buffer
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/routing/pathprocessors/ExtraInfoProcessor.java
Labels: fix

#1822 feat: Remaining border storages
  ors-api/pom.xml
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorage.java
  ors-api/src/main/java/org/heigit/ors/api/config/ExtendedStorageGreenIndex.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/BikeElectricProfileProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/BikeMountainProfileProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/BikeRegularProfileProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/BikeRoadProfileProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/CarProfileProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/DefaultProfileProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/HgvProfileProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/HikingProfileProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/ProfileProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/PublicTransportProfileProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/WalkingProfileProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/WheelchairProfileProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorage.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageBorders.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageCsvIndex.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageGreenIndex.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageHeavyVehicle.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageHereTraffic.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageHillIndex.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageIndex.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageNoiseIndex.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageOsmId.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageRoadAccessRestrictions.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageShadowIndex.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageTollways.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageTrailDifficulty.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageWayCategory.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageWaySurfaceType.java
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageWheelchair.java
  ors-api/src/main/java/org/heigit/ors/api/converters/ExtendedStorageMapDeserializer.java
  ors-api/src/main/java/org/heigit/ors/api/converters/ExtendedStorageMapSerializer.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageBordersTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageCsvIndexTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageGreenIndexTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageHeavyVehicleTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageHereTrafficTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageHillIndexTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageNoiseIndexTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageOsmIdTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageRoadAccessRestrictionsTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageShadowIndexTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageTrailDifficultyTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageWayCategoryTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageWaySurfaceTypeTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/ExtendedStorageWheelchairTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/profile/ProfilePropertiesTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageIndexTest.java
  ors-api/src/test/java/org/heigit/ors/api/config/profile/storages/ExtendedStorageTollwaysTest.java
  ors-api/src/test/java/org/heigit/ors/api/converters/ExtendedStorageMapDeserializerTest.java
  ors-api/src/test/java/org/heigit/ors/api/converters/ExtendedStorageMapSerializerTest.java
  pom.xml
Labels: feature

#1824 chore: Add first lombok implementation
  ors-api/pom.xml
  ors-api/src/main/java/org/heigit/ors/api/config/profile/storages/ExtendedStorage.java
  pom.xml
Labels: ignore-for-release

#1826 refactor: Fix and introduce Lombok usages
  ors-api/src/main/java/org/heigit/ors/api/config/CorsProperties.java
  ors-api/src/main/java/org/heigit/ors/api/config/EndpointsProperties.java
  ors-api/src/main/java/org/heigit/ors/api/util/SystemMessage.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/PreparationProperties.java
Labels: refactor

#1828 fix: docs-docker-example
  docs/run-instance/running-with-docker.md
Labels: fix

#1827 build: update dependencies
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  pom.xml
Labels: build
