Repository GIScience/openrouteservice, pull requests merged in 2024-11, with the labels that each got.

#1883 feat: add Ukrainian translation for the openrouteservice instructions
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/APIEnums.java
  ors-engine/src/main/resources/resources/locales/ors_ua-UA.resources
Labels: feature

#1896 test: compare dates instead of date.toString()
  ors-api/src/test/java/org/heigit/ors/apitests/ORSStartupTest.java
Labels: test

#1898 docs: complete config and grc docu
  docs/.vitepress/config.js
  docs/api-reference/endpoints/directions/extra-info/index.md
  docs/api-reference/endpoints/directions/routing-options.md
  docs/api-reference/endpoints/export/index.md
  docs/api-reference/index.md
  docs/contributing/index.md
  docs/frequently-asked-questions.md
  docs/run-instance/building-from-source.md
  docs/run-instance/configuration/config-overwrite/config-overwrite-merge-defaults.drawio.png
  docs/run-instance/configuration/config-overwrite/config-overwrite-merge-files.drawio.png
  docs/run-instance/configuration/config-overwrite/config-overwrite.drawio.xml
  docs/run-instance/configuration/config-overwrite/config-overwrite.exported.merge-defaults.svg
  docs/run-instance/configuration/config-overwrite/config-overwrite.exported.merge-files.svg
  docs/run-instance/configuration/config-overwrite/readme.txt
  docs/run-instance/configuration/endpoints/index.md
  docs/run-instance/configuration/engine/index.md
  docs/run-instance/configuration/engine/profiles/build.md
  docs/run-instance/configuration/engine/profiles/index.md
  docs/run-instance/configuration/engine/profiles/service.md
  docs/run-instance/configuration/how-to-configure.md
  docs/run-instance/configuration/index.md
  docs/run-instance/configuration/what-to-configure.md
  docs/run-instance/data.md
  docs/run-instance/index.md
  docs/run-instance/running-with-docker.md
  docs/technical-details/country-list.md
  docs/technical-details/graph-repo-client/index.md
  docs/technical-details/travel-speeds/index.md
  ors-api/src/test/java/org/heigit/ors/api/util/ConfigOutputTest.java
Labels: documentation

#1899 feat: Integration tests workflow
  .github/workflows/integration-tests.yml
  docs/.vitepress/config.js
  docs/technical-details/integration-tests.md
  ors-test-scenarios/pom.xml
  ors-test-scenarios/src/test/java/integrationtests/ConfigEnvironmentTest.java
  ors-test-scenarios/src/test/java/integrationtests/ConfigFileTest.java
  ors-test-scenarios/src/test/java/integrationtests/ConfigLookupTest.java
  ors-test-scenarios/src/test/java/integrationtests/GraphRepoTest.java
  ors-test-scenarios/src/test/java/utils/ContainerInitializer.java
  ors-test-scenarios/src/test/java/utils/OneShotGraphBuilderTest.java
  ors-test-scenarios/src/test/java/utils/OrsApiHelper.java
  ors-test-scenarios/src/test/java/utils/OrsConfig.java
  ors-test-scenarios/src/test/java/utils/OrsContainerFileSystemCheck.java
  ors-test-scenarios/src/test/java/utils/TestContainersHelper.java
  ors-test-scenarios/src/test/resources/.dockerignore
  ors-test-scenarios/src/test/resources/Builder.Dockerfile
  ors-test-scenarios/src/test/resources/Dockerfile
  ors-test-scenarios/src/test/resources/jar.Dockerfile
  ors-test-scenarios/src/test/resources/maven.Dockerfile
  ors-test-scenarios/src/test/resources/war.Dockerfile
  pom.xml
Labels: feature

#1900 ci: Streamline the maven caches
  .github/workflows/integration-tests.yml
  .github/workflows/publish-tagged-release.yml
Labels: ci

#1901 ci(dependencies): Streamline maven deps download process
  .github/workflows/publish-tagged-release.yml
  .github/workflows/run_maven_tests.yml
  .github/workflows/vulnerability-scanning.yml
  ors-api/pom.xml
Labels: ci

#1902 ci(integration-tests): Run integration tests only on ready pr
  .github/workflows/integration-tests.yml
  .github/workflows/run_maven_tests.yml
  ors-config.env
  ors-config.yml
Labels: ci

#1903 fix: encapsulate integration tests graph builder
  ors-test-scenarios/src/test/java/integrationtests/OneShotGraphBuilderTest.java
  ors-test-scenarios/src/test/java/utils/ContainerInitializer.java
Labels: fix

#1904 fix: Repair the docker workflow
  .github/utils/yml_config_to_properties_conversion.sh
  .github/workflows/docker-build-and-test.yml
  .github/workflows/integration-tests.yml
  .github/workflows/rpm-build.yml
  .github/workflows/run_maven_tests.yml
  .rpm-packaging/Dockerfile
  .rpm-packaging/ors-config.json
  Dockerfile
  docker-compose.yml
  docker-entrypoint.sh
  docs/run-instance/configuration/engine/profiles/build.md
  docs/run-instance/configuration/how-to-configure.md
  docs/run-instance/data.md
  docs/run-instance/running-jar.md
  docs/run-instance/running-with-docker.md
  ors-api/src/test/java/org/heigit/ors/apitests/common/InitializeGraphsOnce.java
  ors-engine/src/test/resources/ors-config.json
  ors-test-scenarios/src/test/resources/Builder.Dockerfile
  pom.xml
Labels: fix

#1906 chore: cleanup the graph repo classes
  ors-api/src/main/java/org/heigit/ors/api/services/GraphService.java
  ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListener.java
  ors-api/src/test/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListenerTest.java
  ors-api/src/test/java/org/heigit/ors/apitests/ORSStartupTest.java
  ors-engine/src/main/java/org/heigit/ors/exceptions/ORSGraphFileManagerException.java
  ors-engine/src/main/java/org/heigit/ors/exceptions/ORSGraphFileManagerExceptionException.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/GraphInfo.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/GraphManagementRuntimeProperties.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/local/ORSGraphFileManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/remote/FileSystemRepoManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/remote/HttpRepoManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/remote/NamedGraphsRepoStrategy.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/remote/NullRepoManager.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/GraphManagementRuntimePropertiesTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphManagerTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/RepoManagerTestHelper.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/local/ORSGraphFileManagerTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/remote/FileSystemRepoManagerTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/remote/HttpRepoManagerTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/remote/TestAbstractRepoManagerTest.java
Labels: ignore-for-release

#1909 ci(grype): Add missing layer cache for grype
  .github/workflows/vulnerability-scanning.yml
Labels: ci

#1908 refactor: Work in various PR comments
  ors-api/src/main/java/org/heigit/ors/api/Application.java
  ors-api/src/main/java/org/heigit/ors/api/config/ApiEngineProperties.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/ExportAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/IsochronesAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/MatrixAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/RoutingAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/SnappingAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/StatusAPI.java
  ors-api/src/main/java/org/heigit/ors/api/requests/common/APIRequest.java
  ors-api/src/main/java/org/heigit/ors/api/services/ApiService.java
  ors-api/src/main/java/org/heigit/ors/api/services/ExportService.java
  ors-api/src/main/java/org/heigit/ors/api/services/IsochronesService.java
  ors-api/src/main/java/org/heigit/ors/api/services/MatrixService.java
  ors-api/src/main/java/org/heigit/ors/api/services/RoutingService.java
  ors-api/src/main/java/org/heigit/ors/api/services/SnappingService.java
  ors-api/src/test/java/org/heigit/ors/apitests/ORSStartupTest.java
  ors-engine/src/main/java/org/heigit/ors/common/EncoderNameEnum.java
  ors-engine/src/main/java/org/heigit/ors/export/ExportRequest.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/IsochroneRequest.java
  ors-engine/src/main/java/org/heigit/ors/matrix/MatrixRequest.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/GraphProcessContext.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/BordersGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/CsvGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/GreenIndexGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HereTrafficGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HillIndexGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/NoiseIndexGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/RoadAccessRestrictionsGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/ShadowIndexGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/WheelchairGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/snapping/SnappingRequest.java
  ors-engine/src/test/java/org/heigit/ors/common/EncoderNameEnumTest.java
Labels: refactor

#1911 fix: rename MatrixService.uTurnCost back to uTurnCosts
  docs/run-instance/configuration/endpoints/matrix.md
  ors-api/src/main/java/org/heigit/ors/api/config/EndpointsProperties.java
  ors-api/src/main/java/org/heigit/ors/api/services/MatrixService.java
  ors-api/src/main/resources/application.yml
  ors-api/src/test/java/org/heigit/ors/api/services/MatrixServiceTest.java
  ors-engine/src/main/java/org/heigit/ors/matrix/MatrixRequest.java
Labels: fix

#1910 refactor: Config migration sonarlint issues
  ors-engine/src/main/java/org/heigit/ors/config/ElevationProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/BuildProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/EncoderOptionsProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/ExecutionProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/ExtendedStorageProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/PreparationProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/RepoProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/ServiceProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/utils/NonEmptyMapFilter.java
  ors-engine/src/main/java/org/heigit/ors/config/utils/PropertyUtils.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSOSMReader.java
  ors-engine/src/test/java/org/heigit/ors/common/DataAccessEnumTest.java
  ors-engine/src/test/java/org/heigit/ors/config/ExtendedStoragePropertiesTest.java
  ors-engine/src/test/java/org/heigit/ors/config/NonEmptyMapFilterTest.java
  ors-engine/src/test/java/org/heigit/ors/config/profile/ProfilePropertiesTest.java
  ors-engine/src/test/java/org/heigit/ors/config/utils/PropertyUtilsTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperTest.java
Labels: refactor

#1918 chore: update graphhopper to v4.9.5
  CHANGELOG.md
  pom.xml
Labels: ignore-for-release

#1916 build(docker): Remove the go dependency by building yq from source
  Dockerfile
Labels: build
