Repository GIScience/openrouteservice, pull requests merged in 2024-09, with the labels that each got.

#1844 build: update dependencies including GH
  CHANGELOG.md
  ors-api/pom.xml
  pom.xml
Labels: build

#1846 chore: release v8.1.3
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  pom.xml
Labels: ignore-for-release

#1850 refactor(RoutingProfile): move computeRoundTrip to RoutingRequest
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingRequest.java
Labels: refactor

#1811 docs: improvements to external storage documentation
  CHANGELOG.md
  docs/api-reference/endpoints/directions/extra-info/index.md
  docs/api-reference/endpoints/directions/routing-options.md
  docs/run-instance/configuration/ors/engine/profiles.md
  ors-api/src/main/resources/application.yml
  ors-config.env
  ors-config.yml
Labels: documentation
