Repository GIScience/openrouteservice, pull requests merged in 2024-02, with the labels that each got.

#1676 fix: env params logging
  ors-api/src/main/java/org/heigit/ors/api/Application.java
  ors-api/src/main/java/org/heigit/ors/api/ORSEnvironmentPostProcessor.java
Labels: fix

#1678 fix: set correct working directory for maven
  ors-api/pom.xml
Labels: fix

#1679 refactor: remove logging configuration
  .gitignore
  Dockerfile
  ors-api/src/main/resources/application.yml
  ors-api/src/main/resources/log4j-tomcat.properties
  ors-api/src/main/resources/log4j2.yml
Labels: refactor

#1682 fix(isochrones): avoid speed reduction on ways tagged with `access=destination`
  CHANGELOG.md
  ors-api/src/test/java/org/heigit/ors/apitests/isochrones/fast/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/GraphEdgeMapFinder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSWeightingFactory.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/ORSFastestWeighting.java
Labels: fix

#1683 refactor: resolved code issues from docs overhaul
  .rpm-packaging/ors-config.json
  CHANGELOG.md
  docs/installation/Configuration.md
  ors-api/src/main/java/org/heigit/ors/api/EndpointsProperties.java
  ors-api/src/main/java/org/heigit/ors/api/EngineProperties.java
  ors-api/src/main/java/org/heigit/ors/api/ORSEnvironmentPostProcessor.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/StatusAPI.java
  ors-api/src/main/java/org/heigit/ors/api/responses/isochrones/IsochronesResponseInfo.java
  ors-api/src/main/java/org/heigit/ors/api/services/IsochronesService.java
  ors-api/src/main/java/org/heigit/ors/api/util/AppConfigMigration.java
  ors-api/src/main/resources/application.yml
  ors-api/src/test/resources/application-test.yml
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/configuration/RouteProfileConfiguration.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/util/ORSParameters.java
  ors-engine/src/main/java/org/heigit/ors/routing/pathprocessors/ExtraInfoProcessor.java
  ors-engine/src/main/java/org/heigit/ors/util/ProfileTools.java
  ors-engine/src/test/resources/ors-config.json
Labels: refactor

#1669 ci: release artifacts
  .github/workflows/release-artifacts.yml
  .github/workflows/vulnerability-scanning.yml
  CHANGELOG.md
  ors-api/pom.xml
  ors-report-aggregation/pom.xml
Labels: ci

#1687 fix: only run action if config changed
  .github/workflows/config-conversion-automation.yml
Labels: fix

#1690 fix: update links to docs in code
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTE.md
  README.md
  ors-api/src/main/java/org/heigit/ors/api/controllers/RoutingAPI.java
  ors-api/src/main/java/org/heigit/ors/api/requests/common/RequestOptions.java
  ors-api/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RouteRequest.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/json/JSONExtraSummary.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/json/JSONStep.java
Labels: fix

#1689 ci(docker-nightly): move to separate build/publish from test
  .github/workflows/docker-build-and-test.yml
  .github/workflows/docker-nightly-image.yml
  CHANGELOG.md
Labels: ci

#1693 build(maven): Fix the docker-build pipeline
  .github/workflows/docker-build-and-test.yml
  .github/workflows/vulnerability-scanning.yml
  Dockerfile
  ors-api/pom.xml
  ors-report-aggregation/pom.xml
  pom.xml
Labels: build

#1691 fix(exception): Fix the exception output of RoutingProfileManager
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java
Labels: fix

#1692 fix: resolve HOME
  ors-api/src/main/java/org/heigit/ors/api/ORSEnvironmentPostProcessor.java
Labels: fix

#1658 perf(fastisochrones): apply modifications from regular isochrones
  CHANGELOG.md
  ors-api/src/test/java/org/heigit/ors/apitests/isochrones/fast/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/fastisochrones/Contour.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/fast/FastIsochroneMapBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSWeightingFactory.java
  ors-engine/src/main/java/org/opensphere/geometry/algorithm/ConcaveHullOpenSphere.java
  ors-engine/src/main/java/org/opensphere/geometry/triangulation/model/Edge.java
  ors-engine/src/main/java/org/opensphere/geometry/triangulation/model/Triangle.java
  ors-engine/src/main/java/org/opensphere/geometry/triangulation/model/Vertex.java
  ors-engine/src/test/java/org/heigit/ors/fastisochrones/ContourTest.java
Labels: performance

#1694 fix(logging): Enhance logging for here matching progress
  .github/workflows/docker-build-and-test.yml
  README.md
  ors-engine/pom.xml
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HereTrafficGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/util/ProgressBarLogger.java
  ors-engine/src/test/java/org/heigit/ors/util/ProgressBarLoggerTest.java
Labels: fix

#1699 refactor(isochrones): introduce DRYness to isochrone map builders
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/AbstractIsochroneMapBuilder.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/concaveballs/ConcaveBallsIsochroneMapBuilder.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/concaveballs/PointItemVisitor.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/fast/FastIsochroneMapBuilder.java
Labels: refactor

#1703 docs: add FAQ for barrier and CH
  docs/frequently-asked-questions.md
Labels: documentation

#1705 feat: inform about quota reset in FAQ
  docs/frequently-asked-questions.md
Labels: feature
