Repository GIScience/openrouteservice, pull requests merged in 2024-01, with the labels that each got.

#1647 feat: log stats on traffic data matching
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/TrafficGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HereTrafficGraphStorageBuilder.java
Labels: feature

#1640 refactor: move APIEnums into api module
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/APIEnums.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/ExportAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/IsochronesAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/MatrixAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/RoutingAPI.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/SnappingAPI.java
  ors-api/src/main/java/org/heigit/ors/api/converters/APIRequestProfileConverter.java
  ors-api/src/main/java/org/heigit/ors/api/requests/common/APIRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/common/RequestOptions.java
  ors-api/src/main/java/org/heigit/ors/api/requests/export/ExportRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/isochrones/IsochronesRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RequestProfileParamsRestrictions.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RouteRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/snapping/SnappingApiRequest.java
  ors-api/src/main/java/org/heigit/ors/api/responses/common/boundingbox/BoundingBoxFactory.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/gpx/GPXExtensions.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/json/JSONSegment.java
  ors-api/src/main/java/org/heigit/ors/api/services/ApiService.java
  ors-api/src/main/java/org/heigit/ors/api/services/IsochronesService.java
  ors-api/src/main/java/org/heigit/ors/api/services/MatrixService.java
  ors-api/src/main/java/org/heigit/ors/api/services/RoutingService.java
  ors-api/src/test/java/org/heigit/ors/api/converters/APIMatrixRequestProfileConverterTest.java
  ors-api/src/test/java/org/heigit/ors/api/requests/isochrones/IsochronesRequestTest.java
  ors-api/src/test/java/org/heigit/ors/api/requests/matrix/MatrixRequestTest.java
  ors-api/src/test/java/org/heigit/ors/api/requests/routing/APIEnumsTest.java
  ors-api/src/test/java/org/heigit/ors/api/requests/routing/RouteRequestTest.java
  ors-api/src/test/java/org/heigit/ors/api/responses/matrix/json/JSONBasedIndividualMatrixResponseTest.java
  ors-api/src/test/java/org/heigit/ors/api/responses/matrix/json/JSONIndividualMatrixResponseTest.java
  ors-api/src/test/java/org/heigit/ors/api/responses/matrix/json/JSONMatrixResponseTest.java
  ors-api/src/test/java/org/heigit/ors/api/responses/routing/boundingbox/BoundingBoxFactoryTest.java
  ors-api/src/test/java/org/heigit/ors/api/services/APIServiceTest.java
  ors-api/src/test/java/org/heigit/ors/api/services/IsochronesServiceTest.java
  ors-api/src/test/java/org/heigit/ors/api/services/MatrixServiceTest.java
  ors-api/src/test/java/org/heigit/ors/api/services/RoutingServiceTest.java
  ors-api/src/test/java/org/heigit/ors/api/util/SystemMessageTest.java
  ors-api/src/test/java/org/heigit/ors/api/util/TestProvider.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/WheelchairTypesEncoder.java
  ors-engine/src/test/java/org/heigit/ors/routing/RouteResultBuilderTest.java
Labels: refactor

#1623 feat: logging configuration
  Dockerfile
  ors-api/ors-config.yml
  ors-api/src/main/resources/application.yml
  ors-api/src/main/resources/log4j-tomcat.properties
  ors-api/src/main/resources/log4j2.yml
  ors-api/src/main/resources/logs/DEBUG_LOGGING.json
  ors-api/src/main/resources/logs/DEFAULT_LOGGING.json
  ors-api/src/main/resources/logs/PRODUCTION_LOGGING.json
  ors-api/src/test/resources/application-test.yml
  ors-api/src/test/resources/application-unittest.yml
  ors-api/src/test/resources/logs/TEST_LOGGING.json
  ors-api/src/test/resources/logs/UNITTEST_LOGGING.json
Labels: feature

#1650 feat: mmap configuration
  CHANGELOG.md
  ors-api/ors-config.yml
  ors-api/src/main/java/org/heigit/ors/api/EngineProperties.java
  ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListener.java
  ors-api/src/main/resources/application.yml
  ors-engine/pom.xml
  ors-engine/src/main/java/org/heigit/ors/config/EngineConfig.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/configuration/RouteProfileConfiguration.java
  pom.xml
Labels: feature

#1653 chore: adjust to default branch rename (master->main)
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-and-publish.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/run_maven_tests.yml
  .github/workflows/vulnerability-scanning.yml
  CHANGELOG.md
  CONTRIBUTE.md
  Dockerfile
  README.md
  ors-api/src/main/java/org/heigit/ors/api/OpenAPIConfig.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/RoutingAPI.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/gpx/GPXRouteResponse.java
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
Labels: ignore-for-release

#1607 perf(isochrones): improve isochrones performance
  CHANGELOG.md
  ors-api/src/test/java/org/heigit/ors/apitests/isochrones/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/concaveballs/ConcaveBallsIsochroneMapBuilder.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/fast/FastIsochroneMapBuilder.java
  ors-engine/src/main/java/org/heigit/ors/util/GeomUtility.java
Labels: performance

#1656 feat(config): Add workflow for the automatic config conversion
  .github/utils/config_conversion.sh
  .github/workflows/config-conversion-automation.yml
  ors-api/ors-config.yml
Labels: feature

#1660 fix(config): Adjust the conversion script
  .github/utils/config_conversion.sh
  ors-api/src/main/resources/application.yml
Labels: fix

#1657 feat: config cleanup finalize
  .github/utils/config_conversion.sh
  .github/workflows/build-and-publish.yml
  .github/workflows/config-conversion-automation.yml
  Dockerfile
  ors-api/ors-config.yml
  ors-api/src/main/java/org/heigit/ors/api/EngineProperties.java
  ors-api/src/main/java/org/heigit/ors/api/ORSEnvironmentPostProcessor.java
  ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListener.java
  ors-api/src/main/resources/application.yml
  ors-api/src/test/resources/application-test.yml
  ors-config.yml
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java
Labels: feature

#1666 fix: no config loading if test profile is active
  ors-api/src/main/java/org/heigit/ors/api/ORSEnvironmentPostProcessor.java
Labels: fix

#1507 feat: option to build war or fatJar
  CHANGELOG.md
  ors-api/pom.xml
Labels: enhancement | feature :zap:, feature
