Repository GIScience/openrouteservice, pull requests merged in 2024-08, with the labels that each got.

#1832 refactor: replace RouteProfileConfiguration and get tests to work again
  ors-api/src/main/java/org/heigit/ors/api/controllers/StatusAPI.java
  ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListener.java
  ors-api/src/test/java/org/heigit/ors/apitests/common/InitializeGraphsOnce.java
  ors-api/src/test/resources/application-test.yml
  ors-engine/src/main/java/org/heigit/ors/config/ElevationProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/EngineProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/EncoderOptionsProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/ExecutionProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/PreparationProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/ProfileProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/defaults/CarProfileProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/defaults/HgvProfileProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/storages/ExtendedStorageHereTraffic.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/storages/ExtendedStorageHillIndex.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/storages/ExtendedStorageRoadAccessRestrictions.java
  ors-engine/src/main/java/org/heigit/ors/config/utils/NonEmptyObjectFilter.java
  ors-engine/src/main/java/org/heigit/ors/plugins/Plugin.java
  ors-engine/src/main/java/org/heigit/ors/plugins/PluginManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfileLoader.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfilesCollection.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingRequest.java
  ors-engine/src/main/java/org/heigit/ors/routing/configuration/RouteProfileConfiguration.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/GraphProcessContext.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSOSMReader.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/graphbuilders/AbstractGraphBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/graphbuilders/GraphBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/graphbuilders/InFieldGraphBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/HillIndexGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/AbstractGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/BordersGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/CsvGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/GraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/GreenIndexGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HereTrafficGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HillIndexGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/NoiseIndexGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/RoadAccessRestrictionsGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/ShadowIndexGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/WheelchairGraphStorageBuilder.java
  ors-engine/src/test/java/org/heigit/ors/config/NonEmptyObjectFilterTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/RoadAccessRestrictionsGraphStorageBuilderTest.java
Labels: refactor

#1831 build: update dependencies
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-engine/src/main/java/org/heigit/ors/jts/JTS.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/reader/traffic/HereTrafficReader.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/reader/traffic/TrafficLink.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/reader/traffic/TrafficLinkMetadata.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HereTrafficGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/util/GeomUtility.java
  pom.xml
Labels: build

#1837 feat: improve export functionality
  ors-api/src/main/java/org/heigit/ors/api/ORSEnvironmentPostProcessor.java
  ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListener.java
  ors-api/src/test/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListenerTest.java
  ors-engine/src/main/java/org/heigit/ors/config/EngineProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/defaults/DefaultElevationProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/defaults/DefaultEngineProperties.java
  ors-engine/src/test/java/org/heigit/ors/config/EnginePropertiesTest.java
  ors-engine/src/test/java/org/heigit/ors/config/defaults/DefaultElevationPropertiesTest.java
  ors-engine/src/test/java/org/heigit/ors/config/defaults/DefaultEnginePropertiesTest.java
Labels: feature

#1838 chore: release v8.1.2
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  pom.xml
Labels: ignore-for-release

#1839 fix: Upgrade the docker container versions
  Dockerfile
Labels: fix

#1842 fix: Remove the broken board workflow
  .github/workflows/project_automation.yml
Labels: fix
