Repository GIScience/openrouteservice, pull requests merged in 2024-05, with the labels that each got.

#1788 fix: Fix some CVEs
  CHANGELOG.md
  Dockerfile
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  pom.xml
Labels: fix

#1791 fix: relative links in documentation
  CHANGELOG.md
  docs/api-reference/endpoints/directions/extra-info/index.md
  docs/api-reference/endpoints/directions/routing-options.md
  docs/api-reference/endpoints/export/index.md
  docs/api-reference/endpoints/snapping/index.md
  docs/api-reference/index.md
  docs/contributing/index.md
  docs/frequently-asked-questions.md
  docs/run-instance/building-from-source.md
  docs/run-instance/configuration/index.md
  docs/run-instance/configuration/ors/engine/profiles.md
  docs/run-instance/data.md
  docs/run-instance/index.md
  docs/run-instance/running-jar.md
  docs/run-instance/running-war.md
  docs/run-instance/running-with-docker.md
  docs/technical-details/country-list.md
  docs/technical-details/travel-speeds/index.md
Labels: fix

#1790 refactor: Cleanup routing profile management
  ors-api/src/main/java/org/heigit/ors/api/controllers/ExportAPI.java
  ors-api/src/main/java/org/heigit/ors/api/requests/export/ExportApiRequest.java
  ors-api/src/main/java/org/heigit/ors/api/services/ExportService.java
  ors-api/src/main/java/org/heigit/ors/api/services/MatrixService.java
  ors-api/src/main/java/org/heigit/ors/api/services/SnappingService.java
  ors-engine/src/main/java/org/heigit/ors/export/ExportRequest.java
  ors-engine/src/main/java/org/heigit/ors/matrix/MatrixRequest.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingRequest.java
  ors-engine/src/main/java/org/heigit/ors/snapping/SnappingRequest.java
  ors-engine/src/main/java/org/heigit/ors/util/TemporaryUtilShelter.java
Labels: refactor

#1794 fix: way surface type storage
  docs/api-reference/endpoints/directions/extra-info/surface.md
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/fastisochrones/partitioning/storage/CellStorage.java
  ors-engine/src/main/java/org/heigit/ors/fastisochrones/partitioning/storage/IsochroneNodeStorage.java
  ors-engine/src/main/java/org/heigit/ors/fastisochrones/storage/BorderNodeDistanceStorage.java
  ors-engine/src/main/java/org/heigit/ors/fastisochrones/storage/EccentricityStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/SurfaceType.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/BordersGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/CsvGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/GreenIndexGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/HeavyVehicleAttributesGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/HillIndexGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/NoiseIndexGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/OsmIdGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/RoadAccessRestrictionsGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/ShadowIndexGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/SpeedStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/TollwaysGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/TrafficGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/TrailDifficultyScaleGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/WayCategoryGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/WaySurfaceTypeGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/WheelchairAttributesGraphStorage.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/WaySurfaceTypeGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/pathprocessors/ExtraInfoProcessor.java
  ors-engine/src/main/java/org/heigit/ors/routing/util/WaySurfaceDescription.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/storages/WaySurfaceTypeGraphStorageTest.java
Labels: fix

#1799 docs(changelog): add entries for recently merged PR
  CHANGELOG.md
Labels: documentation
