Repository GIScience/openrouteservice, pull requests merged in 2024-06, with the labels that each got.

#1795 feat: efficient many to one matrix
  CHANGELOG.md
  ors-api/src/test/java/org/heigit/ors/apitests/matrix/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/matrix/TargetGraphBuilder.java
  ors-engine/src/main/java/org/heigit/ors/matrix/algorithms/core/CoreMatrixAlgorithm.java
  ors-engine/src/main/java/org/heigit/ors/matrix/algorithms/rphast/RPHASTMatrixAlgorithm.java
  ors-engine/src/main/java/org/heigit/ors/routing/algorithms/RPHASTAlgorithm.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/edgefilters/ch/CHLevelEdgeFilter.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/edgefilters/ch/DownwardSearchEdgeFilter.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/edgefilters/ch/UpwardSearchEdgeFilter.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/edgefilters/core/ExclusiveDownwardSearchEdgeFilter.java
  ors-engine/src/test/java/org/heigit/ors/matrix/rphast/RPHASTMatrixTest.java
  ors-engine/src/test/java/org/heigit/ors/util/ToyGraphCreationUtil.java
Labels: feature

#1796 feat: open up snapping endpoint in public API
  .github/workflows/docker-build-and-test.yml
  CHANGELOG.md
  README.md
  docker-compose.yml
  docs/.vitepress/config.js
  docs/api-reference/endpoints/index.md
  docs/api-reference/endpoints/snapping/index.md
  docs/api-reference/error-codes.md
  docs/api-reference/index.md
  docs/getting-started.md
  docs/run-instance/configuration/json.md
  docs/run-instance/configuration/ors/endpoints/snap.md
  ors-api/src/main/java/org/heigit/ors/api/EndpointsProperties.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/SnappingAPI.java
  ors-api/src/main/java/org/heigit/ors/api/requests/snapping/SnappingApiRequest.java
  ors-api/src/main/java/org/heigit/ors/api/services/SnappingService.java
  ors-api/src/main/java/org/heigit/ors/api/util/AppConfigMigration.java
  ors-api/src/main/resources/application.yml
  ors-api/src/test/java/org/heigit/ors/apitests/snapping/ParamsTest.java
  ors-api/src/test/resources/application-test.yml
  ors-config.env
  ors-config.yml
  ors-engine/src/main/java/org/heigit/ors/snapping/SnappingErrorCodes.java
  ors-engine/src/main/java/org/heigit/ors/snapping/SnappingRequest.java
Labels: feature

#1802 chore: release v8.1.0
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  pom.xml
Labels: ignore-for-release

#1803 chore: post release changes
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  pom.xml
Labels: ignore-for-release

#1805 fix: allow highways under construction for bikes
  CHANGELOG.md
  docs/technical-details/tag-filtering.md
  docs/technical-details/travel-speeds/waytype-speeds.md
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/flagencoders/bike/CommonBikeFlagEncoder.java
  ors-engine/src/main/resources/resources/services/routing/speed_limits/bike.json
Labels: fix
