Repository GIScience/openrouteservice, pull requests merged in 2025-01, with the labels that each got.

#1914 fix: rework dutch translation
  CHANGELOG.md
  ors-engine/src/main/resources/resources/locales/ors_nl-NL.resources
Labels: fix

#1935 docs(topojson-export): add topojson response documentation
  CONTRIBUTE.md
  README.md
  docs/.vitepress/config.js
  docs/.vitepress/theme/index.ts
  docs/api-reference/endpoints/elevation/index.md
  docs/api-reference/endpoints/export/index.md
  docs/api-reference/endpoints/geocoder/index.md
  docs/api-reference/endpoints/optimization/index.md
  docs/api-reference/endpoints/poi/index.md
  docs/api-reference/endpoints/status/index.md
  docs/api-reference/error-codes.md
  docs/api-reference/index.md
  docs/contributing/index.md
  docs/frequently-asked-questions.md
  docs/getting-started.md
  docs/index.md
  docs/public/topojson_qgis.png
  docs/run-instance/configuration/engine/profiles/build.md
  docs/run-instance/configuration/how-to-configure.md
  docs/run-instance/configuration/index.md
  docs/run-instance/data.md
  docs/run-instance/example-setups/en_tomcat-10-ubuntu_22_04.md
  docs/run-instance/running-war.md
  docs/run-instance/running-with-docker.md
  docs/run-instance/system-requirements.md
  docs/technical-details/index.md
  docs/versions/v7.1.1/Frequently-Asked-Questions.md
  docs/versions/v7.1.1/getting-started.md
  docs/versions/v7.1.1/index.md
  docs/versions/v7.1.1/installation/Building-from-Source.md
  ors-api/src/main/java/org/heigit/ors/api/controllers/ExportAPI.java
  ors-api/src/main/java/org/heigit/ors/api/responses/export/json/JsonEdge.java
  ors-api/src/main/java/org/heigit/ors/api/responses/export/json/WeightSerializer.java
  ors-api/src/main/java/org/heigit/ors/api/responses/export/topojson/Properties.java
  ors-api/src/main/java/org/heigit/ors/api/responses/export/topojson/TopoJsonExportResponse.java
  ors-api/src/main/java/org/heigit/ors/api/services/ExportService.java
  ors-api/src/test/java/org/heigit/ors/apitests/export/ParamsTest.java
  ors-engine/src/main/java/org/heigit/ors/export/ExportRequest.java
  package-lock.json
  package.json
Labels: documentation

#1941 docs: fix table
  docs/run-instance/configuration/engine/profiles/build.md
Labels: documentation

#1950 feat: custom model requests
  CHANGELOG.md
  docs/api-reference/error-codes.md
  docs/run-instance/configuration/engine/profiles/build.md
  docs/run-instance/configuration/engine/profiles/service.md
  ors-api/src/main/java/org/heigit/ors/api/APIEnums.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/StatusAPI.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RouteRequest.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RouteRequestCustomModel.java
  ors-api/src/main/java/org/heigit/ors/api/services/RoutingService.java
  ors-api/src/main/resources/application.yml
  ors-api/src/test/java/org/heigit/ors/apitests/ORSStartupTest.java
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
  ors-api/src/test/resources/application-test.yml
  ors-config.env
  ors-config.yml
  ors-engine/src/main/java/org/heigit/ors/config/profile/EncoderOptionsProperties.java
  ors-engine/src/main/java/org/heigit/ors/config/profile/ServiceProperties.java
  ors-engine/src/main/java/org/heigit/ors/routing/RouteRequestParameterNames.java
  ors-engine/src/main/java/org/heigit/ors/routing/RouteSearchParameters.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingErrorCodes.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingRequest.java
  ors-engine/src/main/java/org/heigit/ors/routing/WeightingMethod.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSWeightingFactory.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/ORSPriorityWeighting.java
  ors-engine/src/main/java/org/heigit/ors/util/ProfileTools.java
  ors-engine/src/main/java/org/heigit/ors/util/TemporaryUtilShelter.java
  pom.xml
Labels: feature

#1951 refactor: cleanup routing profile management
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/services/RoutingService.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingRequest.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfig.java
Labels: refactor

#1959 ci: prepare release 7.2.1
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  pom.xml
Labels: ci

#1958 refactor: cleanup class routing profile
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingProfile.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingRequest.java
  ors-test-scenarios/src/test/resources/Builder.Dockerfile
Labels: refactor

#1961 docs: custom model
  docs/.vitepress/config.js
  docs/api-reference/endpoints/directions/custom-models.md
  docs/api-reference/endpoints/directions/index.md
  docs/api-reference/endpoints/status/index.md
  docs/run-instance/configuration/engine/profiles/build.md
  docs/run-instance/configuration/engine/profiles/service.md
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RouteRequestCustomModel.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RouteRequestCustomModelAreas.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RouteRequestCustomModelGeoJSONFeature.java
  ors-api/src/main/java/org/heigit/ors/api/requests/routing/RouteRequestCustomModelGeoJSONPolygonGeometry.java
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingRequest.java
Labels: documentation

#1962 chore: version bump & CHANGELOG
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  ors-test-scenarios/pom.xml
  pom.xml
Labels: ignore-for-release
