Repository GIScience/openrouteservice, pull requests merged in 2025-02, with the labels that each got.

#1966 fix: preparation_mode
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListener.java
Labels: fix

#1969 refactor: adapt value range of CsvGraphStorage
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/CsvGraphStorageBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/HeatStressWeighting.java
Labels: refactor

#1972 docs: add release documentation to CHANGELOG
  CHANGELOG.md
  RELEASE.md
Labels: documentation
