Repository GIScience/openrouteservice, pull requests merged in 2025-04, with the labels that each got.

#2018 build(deps): upgrade spring-boot-starter-parent to 3.4.4
  CHANGELOG.md
  pom.xml
Labels: build

#2022 ci: update actions to latest version
  .github/workflows/deploy-docs.yml
  CHANGELOG.md
  docs/technical-details/api-benchmarks/api-benchmarks.md
Labels: ci

#2023 docs: use latest version number from package.json
  CHANGELOG.md
  RELEASE.md
  docs/.vitepress/config.js
  docs/api-reference/endpoints/export/index.md
  docs/api-reference/index.md
  docs/versions/v8.2.0/api-reference/index.md
  package-lock.json
  package.json
Labels: documentation

#2024 chore: release v9.1.2
  CHANGELOG.md
  ors-api/pom.xml
  ors-benchmark/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  ors-test-scenarios/pom.xml
  package.json
  pom.xml
Labels: ignore-for-release

#2026 chore: restore SNAPSHOT version
  ors-api/pom.xml
  ors-benchmark/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  ors-test-scenarios/pom.xml
  pom.xml
Labels: ignore-for-release

#2027 chore: update base images and yq version in Dockerfile
  CHANGELOG.md
  Dockerfile
Labels: ignore-for-release

#2029 fix: document extra info response change
  docs/api-reference/endpoints/directions/extra-info/index.md
Labels: fix

#2034 fix: github action build default builder image failing
  .github/workflows/integration-tests.yml
  CHANGELOG.md
Labels: fix

#2031 fix: wrong example in WayCategory docs
  CHANGELOG.md
  docs/api-reference/endpoints/directions/extra-info/waycategory.md
Labels: fix

#2042 build: use fixed gatling maven plugin version
  ors-benchmark/pom.xml
Labels: build

#2041 fix: outdated population data link in docs
  CHANGELOG.md
  docs/versions/v7.1.1/Data.md
Labels: fix

#2045 ci: fix broken tests due to missing unittest profile
  ors-api/src/test/java/org/heigit/ors/api/responses/routing/gpx/GPXRouteResponseTest.java
Labels: ci

#2039 docs: add hint to use dedicated editor with configurations
  CHANGELOG.md
  docs/run-instance/configuration/index.md
Labels: documentation

#2028 fix: accept upper and lower case booleans for REBUILD_GRAPHS within the docker setup
  CHANGELOG.md
  docker-entrypoint.sh
Labels: fix

#2037 fix: remove unavailable features from custom models docs
  CHANGELOG.md
  docs/api-reference/endpoints/directions/custom-models.md
Labels: fix

#2047 feat: add access = permit to known access restiction types
  CHANGELOG.md
  docs/api-reference/endpoints/directions/extra-info/road-access-restrictions.md
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/AccessRestrictionType.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/RoadAccessRestrictionsGraphStorageBuilder.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/RoadAccessRestrictionsGraphStorageBuilderTest.java
Labels: feature

#2038 feat: matrix coordinate generator
  CHANGELOG.md
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/generators/CoordinateGeneratorMatrix.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/generators/CoordinateGeneratorRoute.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/generators/CoordinateGeneratorSnapping.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/model/Matrix.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/model/MatrixRepository.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/service/CoordinateSnapper.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/service/MatrixCalculator.java
  ors-benchmark/src/test/java/org/heigit/ors/coordinates_generator/generators/CoordinateGeneratorMatrixTest.java
Labels: feature

#2020 fix: graph build date missing in case route is not found
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/Application.java
  ors-api/src/main/java/org/heigit/ors/api/config/OpenAPIConfig.java
  ors-api/src/main/java/org/heigit/ors/api/controllers/StatusAPI.java
  ors-api/src/main/java/org/heigit/ors/api/errors/CommonResponseEntityExceptionHandler.java
  ors-api/src/main/java/org/heigit/ors/api/responses/common/engineinfo/EngineInfo.java
  ors-api/src/main/java/org/heigit/ors/api/responses/isochrones/IsochronesResponseInfo.java
  ors-api/src/main/java/org/heigit/ors/api/responses/isochrones/geojson/GeoJSONIsochronesResponse.java
  ors-api/src/main/java/org/heigit/ors/api/responses/matrix/MatrixResponseInfo.java
  ors-api/src/main/java/org/heigit/ors/api/responses/matrix/json/JSONMatrixResponse.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/RouteResponseInfo.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/geojson/GeoJSONRouteResponse.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/gpx/GPXExtensions.java
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/json/JSONRouteResponse.java
  ors-api/src/main/java/org/heigit/ors/api/responses/snapping/SnappingResponseInfo.java
  ors-api/src/main/java/org/heigit/ors/api/responses/snapping/geojson/GeoJSONSnappingResponse.java
  ors-api/src/main/java/org/heigit/ors/api/responses/snapping/json/JsonSnappingResponse.java
  ors-api/src/main/java/org/heigit/ors/api/services/GraphService.java
  ors-api/src/main/java/org/heigit/ors/api/servlet/listeners/ORSInitContextListener.java
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/IsochroneMap.java
  ors-engine/src/main/java/org/heigit/ors/isochrones/builders/concaveballs/ConcaveBallsIsochroneMapBuilder.java
  ors-engine/src/main/java/org/heigit/ors/matrix/MatrixResult.java
  ors-engine/src/main/java/org/heigit/ors/matrix/algorithms/rphast/RPHASTMatrixAlgorithm.java
  ors-engine/src/main/java/org/heigit/ors/routing/RouteResult.java
  ors-engine/src/main/java/org/heigit/ors/routing/RouteResultBuilder.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java
  ors-engine/src/main/java/org/heigit/ors/util/AppInfo.java
Labels: fix
