Repository GIScience/openrouteservice, pull requests merged in 2025-03, with the labels that each got.

#1960 fix: ORS_CONFIG_LOCATION not logging with wrong paths
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/ORSEnvironmentPostProcessor.java
  ors-test-scenarios/src/test/java/integrationtests/ConfigEnvironmentTest.java
Labels: fix

#1996 chore: version bump & CHANGELOG
  CHANGELOG.md
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  ors-test-scenarios/pom.xml
  pom.xml
Labels: ignore-for-release

#1998 chore: adapt CHANGELOG
  CHANGELOG.md
  ors-test-scenarios/src/test/java/integrationtests/ConfigEnvironmentTest.java
  ors-test-scenarios/src/test/java/integrationtests/ConfigLookupTest.java
Labels: ignore-for-release

#1999 chore: bump version to next minor release snapshot
  ors-api/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  ors-test-scenarios/pom.xml
  pom.xml
Labels: ignore-for-release

#2001 docs: describe release version strategy and how to copy docker image …
  RELEASE.md
Labels: documentation

#2003 fix: Repair broken integration tests with by pining buildkit 0.15
  .github/workflows/integration-tests.yml
  .github/workflows/vulnerability-scanning.yml
  CHANGELOG.md
  ors-test-scenarios/src/test/java/integrationtests/ConfigEnvironmentTest.java
  ors-test-scenarios/src/test/java/integrationtests/ConfigLookupTest.java
  ors-test-scenarios/src/test/java/utils/ContainerInitializer.java
  ors-test-scenarios/src/test/resources/junit-platform.properties
  pom.xml
Labels: fix

#2006 chore: update to GH version 4.9.7
  pom.xml
Labels: ignore-for-release

#2000 fix: pass extra_info when querying round_trip
  CHANGELOG.md
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ParamsTest.java
  ors-engine/src/main/java/org/heigit/ors/routing/RoutingRequest.java
Labels: fix

#2010 fix: elevation set to false not taken into account
  CHANGELOG.md
  docs/run-instance/configuration/engine/profiles/build.md
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfig.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfigTest.java
Labels: fix

#1978 perf: Gatling benchmarks
  .dockerignore
  .github/workflows/integration-tests.yml
  .gitignore
  Dockerfile
  docs/.vitepress/config.js
  docs/technical-details/api-benchmarks/api-benchmarks.md
  docs/technical-details/api-benchmarks/coordinate-generators.md
  docs/technical-details/api-benchmarks/index.md
  ors-benchmark/pom.xml
  ors-benchmark/src/main/java/org/heigit/ors/benchmark/AbstractLoadTest.java
  ors-benchmark/src/main/java/org/heigit/ors/benchmark/BenchmarkEnums.java
  ors-benchmark/src/main/java/org/heigit/ors/benchmark/Config.java
  ors-benchmark/src/main/java/org/heigit/ors/benchmark/IsochronesRangeLoadTest.java
  ors-benchmark/src/main/java/org/heigit/ors/benchmark/RoutingAlgorithmLoadTest.java
  ors-benchmark/src/main/java/org/heigit/ors/benchmark/exceptions/CommandLineParsingException.java
  ors-benchmark/src/main/java/org/heigit/ors/benchmark/exceptions/RequestBodyCreationException.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/RouteGeneratorApp.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/SnappingGeneratorApp.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/cli/CommandLineParser.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/cli/RouteCommandLineParser.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/cli/SnappingCommandLineParser.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/generators/AbstractCoordinateGenerator.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/generators/CoordinateGeneratorRoute.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/generators/CoordinateGeneratorSnapping.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/model/Point.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/model/Route.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/model/RouteRepository.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/service/MatrixCalculator.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/service/RouteSnapper.java
  ors-benchmark/src/main/java/org/heigit/ors/util/CoordinateGeneratorHelper.java
  ors-benchmark/src/main/java/org/heigit/ors/util/NameUtils.java
  ors-benchmark/src/main/java/org/heigit/ors/util/ProgressBarLogger.java
  ors-benchmark/src/main/java/org/heigit/ors/util/SourceUtils.java
  ors-benchmark/src/main/resources/gatling.conf
  ors-benchmark/src/main/resources/germany_car-foot-bike-hgv_10000_points.csv
  ors-benchmark/src/main/resources/germany_car600-bike10-foot5-hgv600_10000_routes.csv
  ors-benchmark/src/main/resources/logback.xml
  ors-benchmark/src/test/java/org/heigit/ors/benchmark/BenchmarkEnumsTest.java
  ors-benchmark/src/test/java/org/heigit/ors/benchmark/ConfigTest.java
  ors-benchmark/src/test/java/org/heigit/ors/benchmark/IsochronesRangeLoadTestTest.java
  ors-benchmark/src/test/java/org/heigit/ors/coordinates_generator/cli/RouteCommandLineParserTest.java
  ors-benchmark/src/test/java/org/heigit/ors/coordinates_generator/cli/SnappingCommandLineParserTest.java
  ors-benchmark/src/test/java/org/heigit/ors/coordinates_generator/generators/CoordinateGeneratorRouteTest.java
  ors-benchmark/src/test/java/org/heigit/ors/coordinates_generator/generators/CoordinateGeneratorSnappingTest.java
  ors-benchmark/src/test/java/org/heigit/ors/coordinates_generator/model/RouteRepositoryTest.java
  ors-benchmark/src/test/java/org/heigit/ors/coordinates_generator/model/RouteTest.java
  ors-benchmark/src/test/java/org/heigit/ors/util/CoordinateGeneratorHelperTest.java
  ors-benchmark/src/test/java/org/heigit/ors/util/NameUtilsTest.java
  ors-benchmark/src/test/java/org/heigit/ors/util/ProgressBarLoggerTest.java
  ors-benchmark/src/test/java/org/heigit/ors/util/SourceUtilsTest.java
  ors-benchmark/src/test/resources/gatling.conf
  ors-benchmark/src/test/resources/logback-test.xml
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/remote/HttpRepoManagerTest.java
  ors-engine/src/test/java/org/heigit/ors/util/ProgressBarLoggerTest.java
  ors-test-scenarios/src/test/java/utils/ContainerInitializer.java
  ors-test-scenarios/src/test/resources/Builder.Dockerfile
  pom.xml
Labels: performance

#2015 fix: return waytype instead of waytypes for extra info
  CHANGELOG.md
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/routing/pathprocessors/ExtraInfoProcessor.java
Labels: fix

#2017 fix: typos in Turkish translation
  CHANGELOG.md
  ors-engine/src/main/resources/resources/locales/ors_tr-TR.resources
Labels: fix
