Repository GIScience/openrouteservice, pull requests merged in 2025-05, with the labels that each got.

#2050 feat: minio repo client
  CHANGELOG.md
  docs/run-instance/configuration/engine/profiles/repo.md
  docs/technical-details/graph-repo-client/index.md
  ors-engine/pom.xml
  ors-engine/src/main/java/org/heigit/ors/config/profile/RepoProperties.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/GraphBuildInfo.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/GraphManagementRuntimeProperties.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphManager.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/manage/remote/MinioGraphRepoClient.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/ORSGraphManagerTest.java
  ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/manage/remote/MinioRepoManagerTest.java
  pom.xml
Labels: feature

#2052 chore: release v9.2.0
  CHANGELOG.md
  ors-api/pom.xml
  ors-benchmark/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  ors-test-scenarios/pom.xml
  package.json
  pom.xml
Labels: ignore-for-release

#2053 chore: restore SNAPSHOT version
  ors-api/pom.xml
  ors-benchmark/pom.xml
  ors-engine/pom.xml
  ors-report-aggregation/pom.xml
  ors-test-scenarios/pom.xml
  pom.xml
Labels: ignore-for-release

#2054 feat: include OSM data version in the API response
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/responses/common/engineinfo/EngineInfo.java
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
  ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java
  ors-engine/src/main/java/org/heigit/ors/util/AppInfo.java
Labels: feature

#2056 fix: GPX response missing graph and osm dates
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/responses/routing/gpx/GPXExtensions.java
  ors-api/src/test/java/org/heigit/ors/api/responses/routing/gpx/GPXRouteResponseTest.java
  ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java
Labels: fix

#1973 feat: adding maven wrapper to project
  .dockerignore
  .github/workflows/docker-build-and-test.yml
  .github/workflows/integration-tests.yml
  .github/workflows/publish-tagged-release.yml
  .github/workflows/rpm-build.yml
  .github/workflows/run_maven_tests.yml
  .github/workflows/vulnerability-scanning.yml
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  CHANGELOG.md
  Dockerfile
  RELEASE.md
  docs/run-instance/building-from-source.md
  docs/technical-details/api-benchmarks/api-benchmarks.md
  docs/technical-details/api-benchmarks/coordinate-generators.md
  docs/technical-details/integration-tests.md
  mvnw
  mvnw.cmd
  ors-test-scenarios/src/test/java/utils/ContainerInitializer.java
  ors-test-scenarios/src/test/resources/Builder.Dockerfile
  ors-test-scenarios/src/test/resources/maven-entrypoint.sh
  pom.xml
Labels: feature

#2057 docs: add documentation for isochrone attributes
  CHANGELOG.md
  ors-api/src/main/java/org/heigit/ors/api/requests/isochrones/IsochronesRequest.java
Labels: documentation

#2059 feat: matrix generation CLI
  CHANGELOG.md
  ors-benchmark/src/main/java/org/heigit/ors/benchmark/MatrixAlgorithmLoadTest.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/MatrixGeneratorApp.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/cli/MatrixCommandLineParser.java
  ors-benchmark/src/main/java/org/heigit/ors/coordinates_generator/generators/CoordinateGeneratorMatrix.java
  ors-benchmark/src/test/java/org/heigit/ors/coordinates_generator/cli/MatrixCommandLineParserTest.java
Labels: feature

#2061 ci: update deprecated or failing GitHub actions
  .github/workflows/vulnerability-scanning.yml
  CHANGELOG.md
Labels: ci

#2071 fix: hazmat false considered as defined profileParams
  CHANGELOG.md
  ors-engine/src/main/java/org/heigit/ors/routing/RouteSearchParameters.java
  ors-engine/src/test/java/org/heigit/ors/routing/RouteSearchParametersTest.java
Labels: fix
